### ISSUE TITLE
Invalid position given by 'W033'

### ISSUE THREAD

**Issue by Shinigami92** [AtomLinter/linter-jshint#457] opened 2017-07-17 12:49 UTC
JSHint returned a point that did not exist in the document being edited.
Rule: `W033`
Requested point: 41:5

Debug information:
```
Atom version: 1.18.0
linter-jshint version: v3.1.5
JSHint version: jshint v2.9.5
Hours since last Atom restart: 6
Platform: linux
Current file's scopes: [
  "source.js",
  "variable.other.object.js"
]
linter-jshint configuration: {
  "lintInlineJavaScript": true,
  "executablePath": "",
  "disableWhenNoJshintrcFileInPath": false,
  "scopes": [
    "source.js",
    "source.js-semantic"
  ],
  "jshintFileName": ".jshintrc",
  "jshintignoreFilename": ".jshintignore"
}
```

**Comment by Arcanemagus** [comment] 2017-07-17 15:58
Closing as a duplicate of https://github.com/AtomLinter/linter-jshint/issues/422, which is a bit odd as you _should_ have been directed there instead of to creating a new issue. In any case please see that issue for further information on this problem with JSHint.

**Closed by Arcanemagus** 2017-07-17 15:58 UTC
