### ISSUE TITLE
Package.activateConfig is deprecated.

### ISSUE THREAD

**Issue by dr00t** [AtomLinter/linter-jshint#77] opened 2015-05-04 21:47 UTC
Use a config schema instead. See the configuration section
of https://atom.io/docs/latest/hacking-atom-package-word-count and
https://atom.io/docs/api/latest/Config for more details
```
Package.activateConfig (C:\Users\Piotr\AppData\Local\atom\app-0.196.0\resources\app.asar\src\package.js:247:11)
Package.activateNow (C:\Users\Piotr\AppData\Local\atom\app-0.196.0\resources\app.asar\src\package.js:218:14)
<unknown> (C:\Users\Piotr\AppData\Local\atom\app-0.196.0\resources\app.asar\src\package.js:203:30)
Package.measure (C:\Users\Piotr\AppData\Local\atom\app-0.196.0\resources\app.asar\src\package.js:147:15)
```

**Comment by davivcgarcia** [comment] 2015-05-05 03:07
**Looks like the APM repository is not reflecting the current version of the package.** You can fix this issue applying the patch 619308ebd4d3c060471d28ff6a0275b97c7ea40e, which was already merged.

**Comment by iam4x** [comment] 2015-05-05 11:39
I will push a new release with all the deprecated fixed

**Closed by iam4x** 2015-05-05 11:39 UTC

**Comment by Arcanemagus** [comment] 2016-09-26 20:42
Duplicate of #59.
