### ISSUE TITLE
Unexpected end of input

### ISSUE THREAD

**Issue by krzaku12** [AtomLinter/linter-jshint#238] opened 2016-03-21 22:47 UTC
I'm getting this error when linter tries to parse a file.

    [Linter-JSHint] SyntaxError: Unexpected end of input
    at Object.parse (native)
    at Object.<anonymous> (C:/Users/Bartek/.atom/packages/linter-jshint/lib/main.js:116:25)
    at [object Generator].next (native)
    at step (C:\Users\Bartek\.atom\packages\linter-jshint\lib\main.js:3:273)

#115 might be related, but that was on Mac, I'm running Windows 10, and path seems to be set correctly:

    process.env.Path
    "C:\Python27\;C:\Python27\Scripts;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files\nodejs\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;C:\Users\Bartek\AppData\Roaming\npm;C:\Users\Bartek\AppData\Local\atom\bin"

I tried to debug this and with my limited knowledge of node I gathered this: `this.executablePath` in call to `Helpers.execNode` doesn't seem to be set at all, which results in empty `result`. But even replacing `this.executablePath` with the exact location of JSHint doesn't seem to work as well and `result` is still empty.

**Comment by Arcanemagus** [comment] 2016-03-21 22:50
That's being set [here](https://github.com/AtomLinter/linter-jshint/blob/v2.0.3/lib/main.js#L39), if you put a breakpoint there and disable/enable the package are you seeing a reasonable value there? You should see the default value (defined [here](https://github.com/AtomLinter/linter-jshint/blob/v2.0.3/lib/main.js#L14)) unless you have customized it to something else.

**Comment by mooop12** [comment] 2016-03-21 22:56
Yes, I get a default value of `"C:\Users\Bartek\.atom\packages\linter-jshint\node_modules\jshint\bin\jshint"`, but a breakpoint [here](https://github.com/AtomLinter/linter-jshint/blob/v2.0.3/lib/main.js#L111) shows it as `undefined`. Even if I set it manually in the package settings it's still undefined.

**Comment by Arcanemagus** [comment] 2016-03-21 23:05
Ah, this is a babel-ified file, it's going to be something like `_this2` in the first Closure:
![image](https://cloud.githubusercontent.com/assets/427137/13936940/82d59314-ef7e-11e5-9673-61178b1f420d.png)

If you step into the function call (F11) you can see that `command` should be set properly. It looks like it's returning `` for me as well though so something is wrong...

**Comment by chriscasola** [comment] 2016-03-22 15:16
I'm also seeing this problem. This is on windows 7, but only when I launch using the Atom desktop shortcut. If I launch atom at the command line everything works fine.

When I launch with the shortcut, I can step in and see the exec call [here](https://github.com/AtomLinter/linter-jshint/blob/v2.0.3/lib/main.js#L111) timing out. But it times out after the await returns, so [this line](https://github.com/AtomLinter/linter-jshint/blob/v2.0.3/lib/main.js#L116) ends up trying to parse an empty string.

The command and arguments to the exec call look correct in both environments.

I'm not too familiar with how exec works in atom, but let me know if I can try anything else or provide more info.

**Comment by danshapir** [comment] 2016-03-23 17:29
Same issue with Windows 10. Each lint fails with 
```
[Linter-JSHint] SyntaxError: Unexpected end of input(…) 
(anonymous function)	@	/C:/Users/dansh/.atom/packages/linter-jshint/lib/main.js:115
```

That's the
```javascript
parsed = JSON.parse(result)
```

**Comment by Arcanemagus** [comment] 2016-03-28 22:38
An update:
Looks like this is a Windows only bug, I've tested v1.5.4, v1.6.0, and 1.8.0-dev-307944c on Ubuntu with  no issue.

**Comment by rodrigo-martinezd** [comment] 2016-04-03 05:28
I had this problem today and it was the .jshintrc was empty. After adding some options went smoothly.

**Comment by danshapir** [comment] 2016-04-03 06:48
@rodrigo-martinezd Tried, didn't work for me...

**Comment by emileber** [comment] 2016-04-12 15:48
It seems to be a problem with Atom versions over 1.7 on windows. Myself and a coworker had the issue with version 1.7.0-beta5 and I reverted back to the version I had before, which is 1.5.0-beta3 and my coworker tried 1.6.2 without issue.

**Comment by sirlancelot** [comment] 2016-04-13 23:02
I'm on Windows 10. Atom just updated to 1.7 and I'm seeing this issue when I edit JS files. I have a valid `.jshintrc` file and didn't see this error in Atom 1.6.2.

Tracking it down it looks like `execNode` is returning an empty string instead of the JSON string of the JSHint results. Unfortunately, I can't find more detail since I don't know how to step in to `execNode` with the debugger...

**Comment by Arcanemagus** [comment] 2016-04-13 23:27
I've stepped as far down as Atom's BufferedProcess, for some reason only for `jscs` we are getting no data back on the `stdout` stream. I'm not really sure where to debug from here yet and haven't had time to try anything else yet.

**Comment by Arcanemagus** [comment] 2016-04-14 17:02
@craigbuckler pointed out something explicitly over in #257 which was mentioned off hand here but I didn't catch: It looks like this might have started with the v1.7.0 update.

**Comment by Arcanemagus** [comment] 2016-04-14 18:01
Just an update, we've confirmed that this must be a bug in the internal version of Electron inside Atom. If you replace `process.execPath` with a local Node install everything works as expected with no other changes.

**Comment by Arcanemagus** [comment] 2016-04-14 18:20
Filed https://github.com/atom/atom/issues/11471 as it looks to be the Electron bundled within Atom that is the root cause of this.

**Comment by benoitcerrina** [comment] 2016-04-14 19:46
Based on your comment about process.execPath,
I have locally modified the code the following way

        var oldExecPath = process.execPath;
        process.execPath = "E:\\Program Files\\nodejs\\node.exe"
        const result = await Helpers.execNode(
          this.executablePath, parameters, { stdin: fileContents }
        )
        process.execPath = oldExecPath;

It seems to fix it, however as I am very unfamiliar with atom in particular and node in general I am worried about potential impacts (because the call is asynchronous and is using await, the process.execPath is not restored immediately.

Do you think that is a workable fix while waiting for the atom bug to be resolved?

**Comment by Arcanemagus** [comment] 2016-04-14 19:49
You might be safer installing v1.6.2 and disabling auto updates, as I don't know all the impacts of overwriting that either.

You would need to watch for updates to Atom though to catch when this gets fixed on your own after doing that.

**Comment by benoitcerrina** [comment] 2016-04-14 19:59
thanks for the reply

**Comment by Arcanemagus** [comment] 2016-04-15 03:28
Atom v1.7.1 (And v1.8.0-beta1) has been released which should fix this. If you are still having issues please re-open this or file a new issue.

**Closed by Arcanemagus** 2016-04-15 03:28 UTC
Labels: Bug
