### ISSUE TITLE
Improve error message styling

### ISSUE THREAD

**Issue by mohislm** [AtomLinter/linter-jshint#159] opened 2015-08-07 16:39 UTC
- [ ] Needs spacing between labels
- [ ] Line/Column number should inline with the error message

![screenshot](https://cloud.githubusercontent.com/assets/508043/9140707/23ad7616-3d01-11e5-9c51-0cb2f666689a.png)

**Comment by steelbrain** [comment] 2015-08-07 16:41
Which theme are you using?

**Comment by mohislm** [comment] 2015-08-07 19:49
I'm using the default theme: **One Dark**. And my Atom version is **1.0.3**.

**Comment by steelbrain** [comment] 2015-08-07 19:50
For some reasons, I am not able to repro that :(
/cc @arcanemagus

**Comment by Arcanemagus** [comment] 2015-08-07 20:05
I can't reproduce that exactly using OneDark or my regular Seti theme:
![image](https://cloud.githubusercontent.com/assets/427137/9144798/4d59a6e4-3d04-11e5-95c9-aa2793d9a8b8.png)
![image](https://cloud.githubusercontent.com/assets/427137/9144877/e95e2ac4-3d04-11e5-887c-df7dc3fdfaf4.png)


I do see the following oddities though:
* The rule tag is a pixel or two lower on the top than the message type tag
* All 4 text sections are misaligned from each other
* The "at line x col y" text is quite strikingly so...

This would be an issue with the `linter` package though, as linter providers (such as `linter-jshint`) have no control over that.

**Comment by steelbrain** [comment] 2015-08-31 23:11
Closing as it belongs to base linter and not jshint

**Closed by steelbrain** 2015-08-31 23:11 UTC
