### ISSUE TITLE
Invalid position given by 'W033'

### ISSUE THREAD

**Issue by chrispanag** [AtomLinter/linter-jshint#543] opened 2017-12-13 15:57 UTC
JSHint returned a point that did not exist in the document being edited.
Rule: `W033`
Requested point: 45:36

The code is here:
```
const fb = require('../src/Facebook/fbFunctions.js')(FB_PAGE_TOKEN, FB_APP_SECRET);
const stickers = require('../src/Facebook/stickers.js');
const yes_noAnswer = require('./meaningHandler.js').yes_noAnswer;
const _ = require('lodash');
const messages = require('../src/msgTemplates.js');

const dstSort = require('sort-by-distance');

const places = [
  {
    Latitude: 0.0,
    Longitude: 0.0,
    title: "Test",
    image_url: "https://messenger.fb.com/wp-content/uploads/2017/04/3_skol_3.png"
  }
];

function attachmentHandler (id, atts, user) {
  return fb.startsTyping(id).then(() => {
    // Send a message saying that attachments are not supported.
    return Promise.all(_.map(atts, a =>  {
      if ((a.payload.sticker_id == stickers.thumbsUpSmall) || (a.payload.sticker_id == stickers.thumbsUpMedium) || (a.payload.sticker_id == stickers.thumbsUpLarge)) {
        if (user.context.expecting == "yes_no") {
          return yes_noAnswer(id, user, "positive");
        } else {
          return fb.fbMessageDelay(1000, id, `👍`);
        }
      } else if (a.payload.coordinates) {
        return locationHandler(id, user, a.payload.coordinates);
      } else {
        return fb.fbMessageDelay(1000, id, "Μέχρι στιγμής μπορώ να καταλάβω μόνο μηνύματα κειμένου :/").then(() => {
          return messages.howHelp(id);
        });
      }
    }));
  });
}

function locationHandler (id, user, coordinates) {
  db.collection('users').findOneAndUpdate({id: user.id},{ $set: {location: coordinates}});
  return findPlaces(id, user, coordinates);
}

function distance(lat1, lon1, lat2, lon2) {
	var radlat1 = Math.PI * lat1/180
	var radlat2 = Math.PI * lat2/180
	var theta = lon1-lon2
	var radtheta = Math.PI * theta/180
	var dist = Math.sin(radlat1) * Math.sin(radlat2) + Math.cos(radlat1) * Math.cos(radlat2) * Math.cos(radtheta);
	dist = Math.acos(dist)
	dist = dist * 180/Math.PI
	dist = dist * 60 * 1.1515
	return dist * 1.609344;
}

function findPlaces(id, user, coordinates) {
  coordinates = {
    Longitude: coordinates.long,
    Latitude: coordinates.lat
  };
  const opts = {
    yName: 'Longitude',
    xName: 'Latitude'
  };
  var sortedPlaces = dstSort(coordinates, places, opts);
  var place = sortedPlaces[0];
  place.distance  = distance(coordinates.Latitude, coordinates.Longitude, place.Latitude, place.Longitude);
  return messages.sendNearestPlace(id, user, place);
}


module.exports = {
  attachmentHandler,
  locationHandler
};
```

Debug information:
```
Atom version: 1.16.0
linter-jshint version: v3.1.6
JSHint version: jshint v2.9.5
Hours since last Atom restart: 4.9
Platform: linux
Current file's scopes: [
  "source.js",
  "storage.type.const.js"
]
linter-jshint configuration: {
  "esversion": 6,
  "executablePath": "",
  "lintInlineJavaScript": false,
  "disableWhenNoJshintrcFileInPath": false,
  "scopes": [
    "source.js",
    "source.js-semantic"
  ],
  "jshintFileName": ".jshintrc",
  "jshintignoreFilename": ".jshintignore"
}
```

**Comment by Arcanemagus** [comment] 2017-12-13 18:45
Please see the following issue for more details and a temporary workaround.

Thanks for taking the time to report this!

**Comment by Arcanemagus** [comment] 2017-12-13 18:45
Duplicate of #422

**Comment by Arcanemagus** [comment] 2017-12-13 18:46
Note that in your particular case this is caused by the `distance` function being indented with tabs.

**Closed by Arcanemagus** 2017-12-13 18:45 UTC
