### ISSUE TITLE
Last release error: spawn cmd.exe ENOENT

### ISSUE THREAD

**Issue by steak3** [AtomLinter/linter-jshint#191] opened 2016-01-11 11:10 UTC
Hello,

Thanks for this great package.
I have an homemade package that executes some windows commands with a simple child_process.exec. It worked for a long time.
Since the last update of jshint, after openning a file, when I try to perform a command I have this error:

![image](https://cloud.githubusercontent.com/assets/14215758/12231681/a4844214-b859-11e5-808f-5a95bd286a57.png)

To bypass it, I have to restart/refresh Atom, and perform a command without openning another file.

It's like a process conflict. Something changed in that way? Any idea?

EDIT: I should add that there is no problem when I disable linter-jshint package, that's why I came here.

**Comment by Arcanemagus** [comment] 2016-01-11 18:27
Marking this as closed since you already found the root cause and reported it where it needed to be, thanks!

**Closed by Arcanemagus** 2016-01-11 18:27 UTC

**Comment by steak3** [comment] 2016-01-21 13:55
Yes, they seems to have fixed it :ok_hand:
Now I guess it requires to update the dependency version in linter-jshint package?
