### ISSUE TITLE
Invalid position given by 'W043'

### ISSUE THREAD

**Issue by mykiwibuddy** [AtomLinter/linter-jshint#536] opened 2017-11-02 09:34 UTC
JSHint returned a point that did not exist in the document being edited.
Rule: `W043`
Requested point: 111:54

111:54 is the end of the first line below - immediately after the line continuation

```
111    text =  '<div class="checkbox-inline ${width}"> \
112              <label> \
```

Debug information:
```
Atom version: 1.21.2
linter-jshint version: v3.1.6
JSHint version: jshint v2.9.5
Hours since last Atom restart: 0
Platform: darwin
Current file's scopes: [
  "source.js",
  "comment.line.double-slash.js",
  "punctuation.definition.comment.js"
]
linter-jshint configuration: {
  "executablePath": "",
  "lintInlineJavaScript": false,
  "disableWhenNoJshintrcFileInPath": false,
  "scopes": [
    "source.js",
    "source.js-semantic"
  ],
  "jshintFileName": ".jshintrc",
  "jshintignoreFilename": ".jshintignore"
}
```

**Comment by Arcanemagus** [comment] 2017-11-02 15:58
Duplicate of #439

**Closed by Arcanemagus** 2017-11-02 15:58 UTC
