### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by turigeza** [AtomLinter/linter-jshint#293] opened 2016-06-20 16:18 UTC
```
TypeError: Cannot read property 'length' of undefined
    at TextBuffer.module.exports.TextBuffer.lineLengthForRow (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:474:29)
    at Object.<anonymous> (/Users/geza/.atom/packages/linter-jshint/lib/main.js:155:41)
    at [object Generator].next (native)
    at step (/Users/geza/.atom/packages/linter-jshint/lib/main.js:3:273)
```

![screen shot 2016-06-20 at 17 17 40](https://cloud.githubusercontent.com/assets/9335740/16201831/fd26efb8-370a-11e6-98a1-536b657958dc.png)

**Comment by Arcanemagus** [comment] 2016-06-20 18:50
What version of Atom are you using? Is this repeatable and if so can you share the file and `jshint` configuration?

**Comment by turigeza** [comment] 2016-06-20 19:07
Atom is 1.8.0 (latest stable)
![screen shot 2016-06-20 at 20 05 56](https://cloud.githubusercontent.com/assets/9335740/16206889/78c65912-3722-11e6-9e82-cdb123e60912.png)
I go and try and reproduce it ... sorry for the vague report

**Comment by turigeza** [comment] 2016-06-20 19:23
Unfortunately i can not upload the actual file here otherwise I would but here is a link to it
https://drive.google.com/file/d/0B7VdYIkRLxQWbkpFRDBjT2lDd2M/view?usp=sharing

I was on line 152 and i got that error when trying to save the document.

**Comment by turigeza** [comment] 2016-06-20 19:28
Hops I just got an other problem i don't know if related:

![screen shot 2016-06-20 at 20 25 16](https://cloud.githubusercontent.com/assets/9335740/16207486/36a5c984-3725-11e6-8520-3ec3334a2581.png)

I was on line 147 : 0
I was trying to save the document.

Here is the document.
https://drive.google.com/open?id=0B7VdYIkRLxQWa0NhWTV1eWhReVk

**Comment by Arcanemagus** [comment] 2016-06-20 19:44
If the above error happens every time you should file that on `jshint` since it is a bug in their json reporter attempting to stringify a circularly referenced object.

Without being able to reproduce the initial error I'm going to close this since there is no way to debug it. If you see it again _immediately_ save the file and see if you can reproduce it, if so file a new issue 😉.

**Closed by Arcanemagus** 2016-06-20 19:44 UTC

**Comment by turigeza** [comment] 2016-06-20 19:52
Well I shall not bother to report it next time than. I disable your plugin that seems to fix this.
