### ISSUE TITLE
Invalid position given by 'W033'

### ISSUE THREAD

**Issue by ETGgames** [AtomLinter/linter-jshint#468] opened 2017-07-28 17:20 UTC
JSHint returned a point that did not exist in the document being edited.
Rule: `W033`
Requested point: 7:6

Debug information:
```
Atom version: 1.18.0
linter-jshint version: v3.1.5
JSHint version: jshint v2.9.5
Hours since last Atom restart: 0.5
Platform: darwin
Current file's scopes: [
  "source.js",
  "meta.method-call.js",
  "meta.arguments.js",
  "punctuation.definition.arguments.end.bracket.round.js"
]
linter-jshint configuration: {
  "executablePath": "",
  "lintInlineJavaScript": false,
  "disableWhenNoJshintrcFileInPath": false,
  "scopes": [
    "source.js",
    "source.js-semantic"
  ],
  "jshintFileName": ".jshintrc",
  "jshintignoreFilename": ".jshintignore"
}
```

**Comment by Arcanemagus** [comment] 2017-07-28 17:54
Duplicate of #422, please see that issue for more details.

**Closed by Arcanemagus** 2017-07-28 17:54 UTC
Labels: Duplicate
