### ISSUE TITLE
Invalid position given by 'W043'

### ISSUE THREAD

**Issue by ezwaytec** [AtomLinter/linter-jshint#493] opened 2017-08-27 08:12 UTC
JSHint returned a point that did not exist in the document being edited.
Rule: `W043`
Requested point: 371:32

Debug information:
```
Atom version: 1.19.3
linter-jshint version: v3.1.5
JSHint version: jshint v2.9.5
Hours since last Atom restart: 95.9
Platform: win32
Current file's scopes: [
  "source.js",
  "string.quoted.double.js",
  "punctuation.definition.string.end.js"
]
linter-jshint configuration: {
  "executablePath": "",
  "lintInlineJavaScript": false,
  "disableWhenNoJshintrcFileInPath": false,
  "scopes": [
    "source.js",
    "source.js-semantic"
  ],
  "jshintFileName": ".jshintrc",
  "jshintignoreFilename": ".jshintignore"
}
```

**Comment by Arcanemagus** [comment] 2017-08-29 17:54
Please see the following issue for more information.

**Comment by Arcanemagus** [comment] 2017-08-29 17:54
Duplicate of #439

**Closed** 2017-08-29 17:55 UTC
Labels: Duplicate, External
