### ISSUE TITLE
Error with Dockblockr

### ISSUE THREAD

**Issue by peerobo** [AtomLinter/linter-jshint#379] opened 2017-04-28 04:34 UTC
When using with dockblockr - enter a new comment for function definition - I get this error:

```
.atom\packages\linter\lib\linter-registry.js:159 [Linter] Error running JSHint Error: 
.atom\packages\linter-jshint\node_modules\jshint\src\jshint.js:5438
        throw err;
        ^

TypeError: Cannot read property 'id' of null
    at Object.x.nud (C:\Users\Peerobo\.atom\packages\linter-jshint\node_modules\jshint\src\jshint.js:3250:26)
    at expression (C:\Users\Peerobo\.atom\packages\linter-jshint\node_modules\jshint\src\jshint.js:888:34)
    at C:\Users\Peerobo\.atom\packages\linter-jshint\node_modules\jshint\src\jshint.js:2440:23
    at Object.x.led (C:\Users\Peerobo\.atom\packages\linter-jshint\node_modules\jshint\src\jshint.js:1155:16)
    at expression (C:\Users\Peerobo\.atom\packages\linter-jshint\node_modules\jshint\src\jshint.js:926:36)
    at Object.fud (C:\Users\Peerobo\.atom\packages\linter-jshint\node_modules\jshint\src\jshint.js:3697:17)
    at expression (C:\Users\Peerobo\.atom\packages\linter-jshint\node_modules\jshint\src\jshint.js:885:32)
    at statement (C:\Users\Peerobo\.atom\packages\linter-jshint\node_modules\jshint\src\jshint.js:1633:9)
    at statements (C:\Users\Peerobo\.atom\packages\linter-jshint\node_modules\jshint\src\jshint.js:1678:16)
    at itself (C:\Users\Peerobo\.atom\packages\linter-jshint\node_modules\jshint\src\jshint.js:5417:9)
    at Object.x.nud (C:\Users\Peerobo\.atom\packages\linter-jshint\node_modules\jshint\src\jshint.js:3250:26)
    at expression (C:\Users\Peerobo\.atom\packages\linter-jshint\node_modules\jshint\src\jshint.js:888:34)
    at C:\Users\Peerobo\.atom\packages\linter-jshint\node_modules\jshint\src\jshint.js:2440:23
    at Object.x.led (C:\Users\Peerobo\.atom\packages\linter-jshint\node_modules\jshint\src\jshint.js:1155:16)
    at expression (C:\Users\Peerobo\.atom\packages\linter-jshint\node_modules\jshint\src\jshint.js:926:36)
    at Object.fud (C:\Users\Peerobo\.atom\packages\linter-jshint\node_modules\jshint\src\jshint.js:3697:17)
    at expression (C:\Users\Peerobo\.atom\packages\linter-jshint\node_modules\jshint\src\jshint.js:885:32)
    at statement (C:\Users\Peerobo\.atom\packages\linter-jshint\node_modules\jshint\src\jshint.js:1633:9)
    at statements (C:\Users\Peerobo\.atom\packages\linter-jshint\node_modules\jshint\src\jshint.js:1678:16)
    at itself (C:\Users\Peerobo\.atom\packages\linter-jshint\node_modules\jshint\src\jshint.js:5417:9)
```

**Comment by Arcanemagus** [comment] 2017-05-02 22:26
Linting a file with the following contents works just fine for me:

```js
/**
 * [foo description]
 * @param  {[type]} bar [description]
 * @return {[type]}     [description]
 */
function foo(bar) {
  
}
```

From the stack trace this error is entirely within JSHint, if you can determine a file that reproduces the problem then we can get something filed over there for them to fix, but I'm closing this issue as there is nothing that can be done about it here and I can't reproduce it with the information given so far.

**Closed by Arcanemagus** 2017-05-02 22:26 UTC
