### ISSUE TITLE
Error when checking typeof type

### ISSUE THREAD

**Issue by origin1tech** [AtomLinter/linter-jshint#174] opened 2015-10-09 03:23 UTC
When typing the following condition check an error is immediately throw and a popup dialog. The key here is the "typeof" it bombs right after you type the space after it.

    if(typeof somevar === 'number')

If you can point me in the correct direction or have a hunch I'll be happy to sort it out and create a PR.

**Comment by Arcanemagus** [comment] 2015-10-09 04:46
It's a bug bug in `jshint`, see https://github.com/AtomLinter/linter-jshint/issues/171 and https://github.com/jshint/jshint/pull/2508.

**Comment by origin1tech** [comment] 2015-10-09 04:49
Ahh makes sense and I kinda had a hunch to that based on the behavior probably should close this and just refer to #171 <https://github.com/AtomLinter/linter-jshint/issues/171> so as to avoid confusion. 

thx for quick reply!!

Regards,

Carey Hazelton
chazelton@origin1.com <mailto:chazelton@origin1.com>
Confidentiality Notice: The information contained in this electronic transmission, is privileged and confidential and is intended only for the recipient(s) named above. If the reader of this message is not the recipient(s) named above, or an authorized agent of such recipient(s) responsible for delivering it to the intended recipient(s), you are hereby notified that you have received this electronic transmission in error. Any review, dissemination, distribution, or copying of this electronic transmission including any attachments is strictly prohibited. If you have received this electronic transmission in error, please notify the sender immediately. Origin1 Technologies.

**Comment by ricardograca** [comment] 2015-11-18 10:54
I'd just like to update people on this issue. It was fixed in JSHint 2.9.0, but that version had to be removed due to a number of regressions. This issue should be fixed when version 2.9.1 is finally released (hasn't happened yet).

**Comment by Arcanemagus** [comment] 2015-11-18 17:56
Marking this as closed as it's not an issue with `linter-jshint`. I'll be pushing out a new release of this depending on v2.9.1 when that finally gets released.

(/bump #171 if I seem to have forgotten after it gets released :stuck_out_tongue:)

**Closed by Arcanemagus** 2015-11-18 17:56 UTC
