### ISSUE TITLE
Invalid position given by 'W043'

### ISSUE THREAD

**Issue by benativeun** [AtomLinter/linter-jshint#447] opened 2017-07-01 05:31 UTC
JSHint returned a point that did not exist in the document being edited.
Rule: `W043`
Requested start point: 19:24

Debug information:
```
Atom version: 1.18.0
linter-jshint version: v3.1.4
JSHint version: jshint v2.9.5
Hours since last Atom restart: 0.5
Platform: darwin
Current file's scopes: [
  "source.js"
]
linter-jshint configuration: {
  "executablePath": "",
  "lintInlineJavaScript": false,
  "disableWhenNoJshintrcFileInPath": false,
  "scopes": [
    "source.js",
    "source.js-semantic"
  ],
  "jshintFileName": ".jshintrc",
  "jshintignoreFilename": ".jshintignore"
}
```

**Comment by Arcanemagus** [comment] 2017-07-02 19:53
Closing as a duplicate of #439, also your `linter-jshint` package is out of date (the current version would have directed you to that issue 😉).

**Closed by Arcanemagus** 2017-07-02 19:53 UTC
