### ISSUE TITLE
Constant Errors, Not OSX

### ISSUE THREAD

**Issue by steveclason** [AtomLinter/linter-jshint#150] opened 2015-07-22 16:37 UTC
On every change, Windows 7, linter-jshint 1.1.2, Atom 1.0.2, I receive this warning:

"Invalid Result received from JSHint
Check your console for more info. It's a known bug on OSX. See https://github.com/AtomLinter/Linter/issues/726"

Note that I'm not using OSX.

**Comment by steelbrain** [comment] 2015-07-22 16:39
Dupe of https://github.com/AtomLinter/linter-jshint/issues/145
You can try the workarounds in the last comments until a fix is published

**Closed by steelbrain** 2015-07-22 16:39 UTC
