### ISSUE TITLE
Invalid position given by 'W043' (newline issue)

### ISSUE THREAD

**Issue by lapitzasclub** [AtomLinter/linter-jshint#434] opened 2017-06-28 10:19 UTC
JSHint returned a point that did not exist in the document being edited.
Rule: `W043`
Requested start point: 457:116

Debug information:
```
Atom version: 1.18.0
linter-jshint version: v3.1.4
JSHint version: jshint v2.9.5
Hours since last Atom restart: 2.1
Platform: win32
Current file's scopes: [
  "source.js"
]
linter-jshint configuration: {
  "executablePath": "",
  "lintInlineJavaScript": false,
  "disableWhenNoJshintrcFileInPath": false,
  "scopes": [
    "source.js",
    "source.js-semantic"
  ],
  "jshintFileName": ".jshintrc",
  "jshintignoreFilename": ".jshintignore"
}
```

**Comment by Arcanemagus** [comment] 2017-06-28 16:28
Is your file indented using tabs?

**Comment by lapitzasclub** [comment] 2017-06-29 06:18
I noticed this happen when I use the line scaper in JS:

```
myObj.buttons().
      .appendTo('someText1 \
      someText2');
```

**Comment by Arcanemagus** [comment] 2017-06-29 16:28
@lapitzasclub That doesn't answer the question of whether your code is indented with tabs 😛.

If your file _isn't_ then this is a different bug from the current known one, and I'm sure the JSHint developers would like to know about it. Are you able to share the file you saw this one (assuming it still shows the message), or are you able to create a minimal reproduction case?

**Comment by lapitzasclub** [comment] 2017-06-29 18:14
No, is indented with spaces.

I can reproduce it every time I escape a line break in a ".js" file. For example:

```
var myText = "Line part1 \
Line part2"
```

**Comment by Arcanemagus** [comment] 2017-06-29 23:48
Confirmed locally, reproduced with `jshint` CLI command. I'll file an issue on their repo tomorrow if you don't beat me to it 😉.

**Comment by lapitzasclub** [comment] 2017-06-30 06:27
Ok, thanks a lot.

**Comment by Arcanemagus** [comment] 2017-07-12 20:48
Looks like this is fixed in JSHint's master branch, their next release will include it so I'm marking this as closed. Thanks for reporting it!

**Closed by Arcanemagus** 2017-07-12 20:48 UTC
Labels: External
