### ISSUE TITLE
write EPIPE after the upgrade to 1.0.0

### ISSUE THREAD

**Issue by Leftyx** [AtomLinter/linter-jshint#117] opened 2015-07-10 11:34 UTC
When saving a javascript file:
```
Error: write EPIPE
  at exports._errnoException (util.js:734:11)
  at Socket._writeGeneric (net.js:668:26)
  at Socket._write (net.js:687:8)
  at doWrite (_stream_writable.js:295:12)
  at writeOrBuffer (_stream_writable.js:282:5)
  at Socket.Writable.write (_stream_writable.js:210:11)
  at Socket.write (net.js:612:40)
  at C:\Users\MyUser\.atom\packages\linter-jshint\node_modules\atom-linter\lib\helpers.coffee:22:30
  at Object.module.exports.Helpers.exec (C:\Users\MyUser\.atom\packages\linter-jshint\node_modules\atom-linter\lib\helpers.coffee:14:16)
  at Object.provider.lint (C:\Users\MyUser\.atom\packages\linter-jshint\lib\main.coffee:21:24)
  at C:\Users\MyUser\.atom\packages\linter\lib\editor-linter.coffee:69:26
  at currentLinter (C:\Users\MyUser\.atom\packages\linter\lib\editor-linter.coffee:68:20)
  at C:\Users\MyUser\.atom\packages\linter\lib\editor-linter.coffee:82:23
  at Set.forEach (native)
  at EditorLinter.triggerLinters (C:\Users\MyUser\.atom\packages\linter\lib\editor-linter.coffee:64:26)
  at C:\Users\MyUser\.atom\packages\linter\lib\editor-linter.coffee:57:27
```

and

```
'C:\Users\MyUser.atom\packages\linter-jshint\node_modules.bin\jshint' could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process.
```

Tried uninstall and install again but got the same problem.  
Rolled back to version 0.1.7.

**Comment by SebastianMueller87** [comment] 2015-07-10 12:24
Got the same after the update to 1.0.0 
Got an additional advice:

'C:\Users\MyUser.atom\packages\linter-jshint\node_modules.bin\jshint' could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process.

**Comment by petersandor** [comment] 2015-07-10 13:05
I have the same issue after update.

**Comment by rbaprado** [comment] 2015-07-10 13:54
+1

**Comment by steelbrain** [comment] 2015-07-10 14:11
Just pushed a patch release, does it work for you?

**Comment by yoctozepto** [comment] 2015-07-10 14:13
I have updated to 1.0.1 but still have this issue.

**Comment by yoctozepto** [comment] 2015-07-10 14:18
...blah...blah...User.atom\packages\linter-jshint\node_modules.bin\jshint
should be
    ...blah...blah...User\.atom\packages\linter-jshint\node_modules\.bin\jshint
i.e. two missing path separators.

Also, this is a Windows machine so it really should be calling jshint.cmd file...

**Comment by iam4x** [comment] 2015-07-10 14:21
@steelbrain Do you use `path.sep` for joining the paths for windows compability?

**Comment by steelbrain** [comment] 2015-07-10 14:21
@iam4x
```
require('path').join(__dirname, '..', 'node_modules', '.bin', 'jshint')
```

**Comment by cristian-t** [comment] 2015-07-10 14:30
Under Windows 7, using this fixed the error:

```require('path').join(__dirname, '..', 'node_modules', '.bin', 'jshint.cmd')```

**Comment by yoctozepto** [comment] 2015-07-10 14:33
Yes, somehow Atom does not display some path separators in error messages, it's odd...
So the problem is, as I mentioned previously, it should be calling .cmd as this is Windows.

**Comment by steelbrain** [comment] 2015-07-10 14:45
Ahh! `.cmd`
I'll fix it right away

**Comment by steelbrain** [comment] 2015-07-10 15:04
Fixed by https://github.com/AtomLinter/linter-jshint/commit/0f7f2360deee5aed1cc520e444d37f2ddaa862a7

**Closed by steelbrain** 2015-07-10 15:04 UTC

**Comment by rbaprado** [comment] 2015-07-10 15:13
What I am seeing here (1.0.2):
```
Error: write EPIPE
    at exports._errnoException (util.js:734:11)
    at Socket._writeGeneric (net.js:668:26)
    at Socket._write (net.js:687:8)
    at doWrite (_stream_writable.js:295:12)
    at writeOrBuffer (_stream_writable.js:282:5)
    at Socket.Writable.write (_stream_writable.js:210:11)
    at Socket.write (net.js:612:40)
    at /C:/Users/buzz/.atom/packages/linter-jshint/node_modules/atom-linter/lib/helpers.coffee:44:32
    at Object.module.exports.Helpers.exec (/C:/Users/buzz/.atom/packages/linter-jshint/node_modules/atom-linter/lib/helpers.coffee:30:14)
    at Object.provider.lint (C:\Users\buzz\.atom\packages\linter-jshint\lib\main.coffee:25:26)

'C:\Users\buzz.atom\packages\linter-jshint\node_modules.bin\jshint' could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process.

**Comment by steelbrain** [comment] 2015-07-10 15:14
@rbaprado if you're on OSX can you repro after spawning atom from CLI

**Comment by yoctozepto** [comment] 2015-07-10 15:15
@steelbrain He's on Windows.
@rbaprado It is fixed in 1.0.3 (you have 1.0.2).

**Comment by rbaprado** [comment] 2015-07-10 15:15
@steelbrain Atom just pulled 1.0.3 and I am not seeing the issue anymore. Sorry for the noise.

**Comment by steelbrain** [comment] 2015-07-10 15:16
Naa it's fine, I just love bug hunting :)
