### ISSUE TITLE
Invalid position given by 'W033'

### ISSUE THREAD

**Issue by cargy** [AtomLinter/linter-jshint#453] opened 2017-07-06 11:34 UTC
JSHint returned a point that did not exist in the document being edited.
Rule: `W033`
Requested start point: 23:115

Debug information:
```
Atom version: 1.18.0
linter-jshint version: v3.1.4
JSHint version: jshint v2.9.5
Hours since last Atom restart: 0
Platform: win32
Current file's scopes: [
  "source.js",
  "storage.type.var.js"
]
linter-jshint configuration: {
  "executablePath": "",
  "lintInlineJavaScript": false,
  "disableWhenNoJshintrcFileInPath": false,
  "scopes": [
    "source.js",
    "source.js-semantic"
  ],
  "jshintFileName": ".jshintrc",
  "jshintignoreFilename": ".jshintignore"
}
```

**Comment by Arcanemagus** [comment] 2017-07-06 16:01
Closing as a duplicate of https://github.com/AtomLinter/linter-jshint/issues/422, please see that issue for more information (and update `linter-jshint` 😉).

**Closed by Arcanemagus** 2017-07-06 16:01 UTC
