### ISSUE TITLE
Invalid position given by 'W033'

### ISSUE THREAD

**Issue by rickmutua** [AtomLinter/linter-jshint#503] opened 2017-09-07 09:40 UTC
JSHint returned a point that did not exist in the document being edited.
Rule: `W033`
Requested point: 36:43

Debug information:
```
Atom version: 1.19.3
linter-jshint version: v3.1.5
JSHint version: jshint v2.9.5
Hours since last Atom restart: 2
Platform: linux
Current file's scopes: [
  "source.js"
]
linter-jshint configuration: {
  "executablePath": "",
  "lintInlineJavaScript": false,
  "disableWhenNoJshintrcFileInPath": false,
  "scopes": [
    "source.js",
    "source.js-semantic"
  ],
  "jshintFileName": ".jshintrc",
  "jshintignoreFilename": ".jshintignore"
}
```

**Comment by Arcanemagus** [comment] 2017-09-07 15:46
Duplicate of #502

**Comment by Arcanemagus** [comment] 2017-09-07 15:46
Please see that issue for a temporary workaround and further details on the issue with JSHint.

**Closed by Arcanemagus** 2017-09-07 15:46 UTC
