### ISSUE TITLE
Invalid position given by 'W043'

### ISSUE THREAD

**Issue by gyutaesi** [AtomLinter/linter-jshint#495] opened 2017-08-31 10:12 UTC
JSHint returned a point that did not exist in the document being edited.
Rule: `W043`
Requested point: 150:37

Debug information:
```
Atom version: 1.19.4
linter-jshint version: v3.1.5
JSHint version: jshint v2.9.5
Hours since last Atom restart: 0
Platform: win32
Current file's scopes: [
  "source.js",
  "comment.block.js"
]
linter-jshint configuration: {
  "executablePath": "",
  "lintInlineJavaScript": false,
  "disableWhenNoJshintrcFileInPath": false,
  "scopes": [
    "source.js",
    "source.js-semantic"
  ],
  "jshintFileName": ".jshintrc",
  "jshintignoreFilename": ".jshintignore"
}
```

**Comment by Arcanemagus** [comment] 2017-08-31 17:06
Duplicate of #439

**Comment by Arcanemagus** [comment] 2017-08-31 17:06
Please see the above issue for more information on this, thanks for taking the time to report it though!

**Closed by Arcanemagus** 2017-08-31 17:06 UTC
