### ISSUE TITLE
Invalid position given by 'W030'

### ISSUE THREAD

**Issue by lcl-101** [AtomLinter/linter-jshint#729] opened 2019-04-19 04:29 UTC
JSHint returned a point that did not exist in the document being edited.
Rule: `W030`
Requested point: 48:26

Debug information:
```
Atom version: 1.36.0
linter-jshint version: v3.1.15
JSHint version: jshint v2.10.2
Hours since last Atom restart: 0
Platform: darwin
Current file's scopes: [
  "source.js",
  "comment.line"
]
linter-jshint configuration: {
  "executablePath": "",
  "lintInlineJavaScript": false,
  "disableWhenNoJshintrcFileInPath": false,
  "scopes": [
    "source.js",
    "source.js-semantic"
  ],
  "jshintFileName": ".jshintrc",
  "jshintignoreFilename": ".jshintignore"
}
```

**Comment by Arcanemagus** [comment] 2019-04-22 20:01
Please see the following issue for more information.

**Comment by Arcanemagus** [comment] 2019-04-22 20:01
Duplicate of #421

**Closed by Arcanemagus** 2019-04-22 20:01 UTC
