### ISSUE TITLE
Long running process and high CPU usage

### ISSUE THREAD

**Issue by petecoop** [AtomLinter/linter-jshint#95] opened 2015-05-26 16:19 UTC
Over the past few days I've noticed my fans starting to blaze up after a while. It seems to be down to this plugin - here's a couple of instances of long running processes using a lot of CPU taken from `ps aux`:

```
USER              PID  %CPU %MEM      VSZ    RSS   TT  STAT STARTED      TIME COMMAND
pete            18985 100.0  0.6  3105256  51124   ??  R     4:21pm  50:43.33 /Applications/Atom.app/Contents/Resources/app/apm/bin/node /Users/pete/.atom/packages/linter-jshint/node_modules/jshint/bin/jshint --verbose --extract=auto /var/folders/s4/3c8wrl2x6mv55gj8krrqr1bw0000gn/T/AtomLinter115426-18022-1dyfumisource.js/datatable.js
pete            18706  99.2  0.6  3097064  51152   ??  R     4:19pm  52:56.01 /Applications/Atom.app/Contents/Resources/app/apm/bin/node /Users/pete/.atom/packages/linter-jshint/node_modules/jshint/bin/jshint --verbose --extract=auto /var/folders/s4/3c8wrl2x6mv55gj8krrqr1bw0000gn/T/AtomLinter115426-18022-1w2lebjsource.js/datatable.js
```

The `datatable.js` file it seemed to be struggling with was using ES6 syntax, was also from an instance of atom that I had closed.

**Comment by dustinmoorenet** [comment] 2015-05-26 17:25
I am also experiencing this issue as well. I have noticed it on two separate machine. One with ES6 syntax and one without. This has been happening since at least Thursday (5/21). If I kill the node processes and disable linter-jshint in Atom, all is good. The issue happens within an hour of coding in Atom.

```
dustin          64597 100.5  0.6  3060200  54360   ??  R    12:07PM   7:51.77 /Applications/Atom.app/Contents/Resources/app/apm/bin/node /Users/dustin/.atom/packages/linter-jshint/node_modules/jshint/bin/jshint --verbose --extract=auto -c /Users/dustin/dev/pappy/.jshintrc /var/folders/s7/4cpvsng5761dxc_cr549z9c80000gn/T/AtomLinter115426-64317-13g085jsource.js/EndiciaStatus.js
dustin          64596 100.5  0.6  3060200  51280   ??  R    12:07PM   7:54.66 /Applications/Atom.app/Contents/Resources/app/apm/bin/node /Users/dustin/.atom/packages/linter-jshint/node_modules/jshint/bin/jshint --verbose --extract=auto -c /Users/dustin/dev/pappy/.jshintrc /var/folders/s7/4cpvsng5761dxc_cr549z9c80000gn/T/AtomLinter115426-64317-13848z3source.js/EndiciaStatus.js
```

**Comment by jeffcharles** [comment] 2015-05-26 20:04
Also experiencing this issue.

After exiting atom, I see this:

```
14325 ??        33:29.15 /Applications/Atom.app/Contents/Resources/app/apm/bin/node /Users/jcharles/.atom/packages/linter-jshint/node_modules/jshint/bin/jshint --verbose --extract=auto -c /Users/jcharles/projects/cabinet/.jshintrc --exclude-path /Users/jcharles/projects/cabinet/.jshintignore /var/folders/zr/y17gd1hn2bs4nrw520y9j9cdz3r4xx/T/AtomLinter115426-1587-t4zno5source.js/logging.js
14329 ??        33:28.17 /Applications/Atom.app/Contents/Resources/app/apm/bin/node /Users/jcharles/.atom/packages/linter-jshint/node_modules/jshint/bin/jshint --verbose --extract=auto -c /Users/jcharles/projects/cabinet/.jshintrc --exclude-path /Users/jcharles/projects/cabinet/.jshintignore /var/folders/zr/y17gd1hn2bs4nrw520y9j9cdz3r4xx/T/AtomLinter115426-1587-1kxy8z7source.js/logging.js
14331 ??        33:23.46 /Applications/Atom.app/Contents/Resources/app/apm/bin/node /Users/jcharles/.atom/packages/linter-jshint/node_modules/jshint/bin/jshint --verbose --extract=auto -c /Users/jcharles/projects/cabinet/.jshintrc --exclude-path /Users/jcharles/projects/cabinet/.jshintignore /var/folders/zr/y17gd1hn2bs4nrw520y9j9cdz3r4xx/T/AtomLinter115426-1587-1vzn6gsource.js/logging.js
14333 ??        33:21.40 /Applications/Atom.app/Contents/Resources/app/apm/bin/node /Users/jcharles/.atom/packages/linter-jshint/node_modules/jshint/bin/jshint --verbose --extract=auto -c /Users/jcharles/projects/cabinet/.jshintrc --exclude-path /Users/jcharles/projects/cabinet/.jshintignore /var/folders/zr/y17gd1hn2bs4nrw520y9j9cdz3r4xx/T/AtomLinter115426-1587-1chkki5source.js/logging.js
14335 ??        33:18.99 /Applications/Atom.app/Contents/Resources/app/apm/bin/node /Users/jcharles/.atom/packages/linter-jshint/node_modules/jshint/bin/jshint --verbose --extract=auto -c /Users/jcharles/projects/cabinet/.jshintrc --exclude-path /Users/jcharles/projects/cabinet/.jshintignore /var/folders/zr/y17gd1hn2bs4nrw520y9j9cdz3r4xx/T/AtomLinter115426-1587-fv1a2usource.js/logging.js
14339 ??        33:14.16 /Applications/Atom.app/Contents/Resources/app/apm/bin/node /Users/jcharles/.atom/packages/linter-jshint/node_modules/jshint/bin/jshint --verbose --extract=auto -c /Users/jcharles/projects/cabinet/.jshintrc --exclude-path /Users/jcharles/projects/cabinet/.jshintignore /var/folders/zr/y17gd1hn2bs4nrw520y9j9cdz3r4xx/T/AtomLinter115426-1587-7of0uvsource.js/logging.js
14341 ??        33:11.53 /Applications/Atom.app/Contents/Resources/app/apm/bin/node /Users/jcharles/.atom/packages/linter-jshint/node_modules/jshint/bin/jshint --verbose --extract=auto -c /Users/jcharles/projects/cabinet/.jshintrc --exclude-path /Users/jcharles/projects/cabinet/.jshintignore /var/folders/zr/y17gd1hn2bs4nrw520y9j9cdz3r4xx/T/AtomLinter115426-1587-ca9lrmsource.js/logging.js
14343 ??        33:07.54 /Applications/Atom.app/Contents/Resources/app/apm/bin/node /Users/jcharles/.atom/packages/linter-jshint/node_modules/jshint/bin/jshint --verbose --extract=auto -c /Users/jcharles/projects/cabinet/.jshintrc --exclude-path /Users/jcharles/projects/cabinet/.jshintignore /var/folders/zr/y17gd1hn2bs4nrw520y9j9cdz3r4xx/T/AtomLinter115426-1587-1ra8m7hsource.js/logging.js
```

Not sure why these are all still running even after exiting Atom.

**Comment by Uhsac** [comment] 2015-05-28 08:45
I think I have the same issue : atom/atom#6970

**Comment by dustinmoorenet** [comment] 2015-05-28 15:12
It is my impression that a jshint process is run for each file that needs hinting and then exits, and our problem is that the process gets stuck. The process shouldn't be running for any amount of time. I am keeping my Mac cool by running `pkill -9 -f jshint` every time the fan kicks on. You can double check what you are about to kill by running `pgrep -f jshint`

**Comment by davewasmer** [comment] 2015-05-29 14:34
I've noticed the same. Downgrading to 1.4.0 (`apm install linter-jshint@1.4.0`) _seems_ to resolve the issue (for now at least).

Looking at the commit history, it looks like it would have to be one of these two one-line changes that introduced the problem:

* 20bc6805f4154ea27f3b7984f1505900b2a64b02
* 7ee35d87b5aa06fd8beab0f78964418c5e61d282

Unfortunately, I'm not familiar enough with Atom to guess which. Perhaps @kevinsawicki could weigh in.

**Comment by textedit** [comment] 2015-05-30 16:10
Same issue here :(

**Comment by atom-project** [comment] 2015-05-30 23:29
+1

**Comment by steelbrain** [comment] 2015-05-30 23:30
Gonna fix this in the transition of making this linter plus API compatible.

**Comment by antonosmond** [comment] 2015-06-01 22:44
I've had the same problem - to reproduce:
1. open a new atom file
2. ensure the source type is JavaScript
3. Type 'function'
It's at the point you type function that a node process gets launched.
Hope this helps.

**Comment by petecoop** [comment] 2015-06-01 22:55
@antonosmond brilliant fix :+1:

**Comment by davewasmer** [comment] 2015-06-02 14:08
Scratch my comment - 1.4 seems to have the problem as well.

@kevinsawicki @iam4x is there any other diagnostic / debugging info I could provide to make this easier to track down?

**Comment by antonosmond** [comment] 2015-06-03 11:51
I think the following commit might be the problem:
https://github.com/antonosmond/linter-jshint/commit/20bc6805f4154ea27f3b7984f1505900b2a64b02
Not sure if it causes it to loop or something but I've removed the super and so far the problem appears to have gone away. I'll try it out for a while and if the problem has gone I'll submit a pull request.

**Comment by davewasmer** [comment] 2015-06-03 12:41
@antonosmond That looks like one of the two changes in 1.5. I tried rolling back to 1.4 for a week or so, saw no improvement. Curious to hear how it goes for you.

**Comment by kevinsawicki** [comment] 2015-06-03 22:59
Are all files causing this or only certain files for people?

Or some steps that are consistently reproducible?

I'm not experiencing it using a simple JS file with a couple lines that have missing semicolons to generate some warnings.

**Comment by kevinsawicki** [comment] 2015-06-03 23:17
Can people run `cat ~/.atom/packages/linter-jshint/node_modules/jshint/package.json | grep version` and report the version of `jshint` being used?

**Comment by kevinsawicki** [comment] 2015-06-03 23:23
It looks like some hangs were fixed in jshint 2.8, https://github.com/jshint/jshint/issues/2383

I published `0.1.6` which upgrades to this jshint version, please let me know if you still experience this problem after upgrading this version and restarting Atom.

**Comment by antonosmond** [comment] 2015-06-04 07:38
I've upgraded to 0.1.6 and seems fine so far. Thanks!

**Comment by Nicolab** [comment] 2015-06-04 07:56
Me too, I've upgraded to 0.1.6 / jshint 2.8 and I no longer have this problem.
Thanks :)

**Comment by Uhsac** [comment] 2015-06-04 08:17
Looks ok for me too but I will edit at the end of the day to confirm

**Comment by textedit** [comment] 2015-06-04 10:17
Yup, works fine here with ```0.1.6```. Thanks!

**Comment by formula1** [comment] 2015-06-06 00:17
Yay :)

Something else I noticed was it doesn't  run right when you switch files
This is a good thing IMO as at times opening up a minimified file causes locks

**Comment by steelbrain** [comment] 2015-07-13 11:54
Closing as presumed fixed by the latest rewrite.

**Closed by steelbrain** 2015-07-13 11:54 UTC
Labels: bug
