### ISSUE TITLE
Unexpected end of input

### ISSUE THREAD

**Issue by lifepillar** [AtomLinter/linter-jshint#116] opened 2015-07-10 10:28 UTC
I have just installed v1.0.0 and as soon as I save a JavaScript file I get this error:

```
Unexpected end of input
SyntaxError: Unexpected end of input
  at Object.parse (native)
  at /Users/me/.atom/packages/linter-jshint/lib/main.coffee:22:23
```

**Comment by varemenos** [comment] 2015-07-10 10:32
Same here, it keeps spamming this error notification every time it tries to lint

**Comment by steelbrain** [comment] 2015-07-10 10:36
I am unable to repro this, can someone do `coffeelint ~/.atom/packages/linter-jshint/lib` and post the results?

**Comment by steelbrain** [comment] 2015-07-10 10:37
Dupe of https://github.com/AtomLinter/linter-jshint/issues/115

**Closed by steelbrain** 2015-07-10 10:37 UTC

**Comment by kaesetoast** [comment] 2015-07-10 10:39
Sure :-)

```
➜  ay.dev master ✗ coffeelint ~/.atom/packages/linter-jshint/lib
  ✗ /home/philipp/.atom/packages/linter-jshint/lib/main.coffee
     ✗ #9: Line exceeds maximum allowed length. Length is 88, max is 80.
     ✗ #20: Line exceeds maximum allowed length. Length is 95, max is 80.
     ✗ #21: Line exceeds maximum allowed length. Length is 83, max is 80.
     ✗ #22: Line exceeds maximum allowed length. Length is 91, max is 80.

✗ Lint! » 4 errors and 0 warnings in 1 file
```

**Comment by varemenos** [comment] 2015-07-10 10:46
```
  ✗ /Users/adonisk/.atom/packages/linter-jshint/lib/main.coffee
     ✗ #9: Line exceeds maximum allowed length. Length is 88, max is 80.
     ✗ #20: Line exceeds maximum allowed length. Length is 95, max is 80.
     ✗ #21: Line exceeds maximum allowed length. Length is 83, max is 80.
     ✗ #22: Line exceeds maximum allowed length. Length is 91, max is 80.

✗ Lint! » 4 errors and 0 warnings in 1 file
```

**Comment by adarhef** [comment] 2015-07-10 13:08
<img width="682" alt="screen shot 2015-07-10 at 4 07 35 pm" src="https://cloud.githubusercontent.com/assets/6278531/8619237/da1a10d4-271d-11e5-9642-d81788f2c3de.png">

Here you go. Seems weird, I didn't realize there was strict enforcement of line length.

**Comment by daaren-urthling** [comment] 2015-07-16 11:00
My 2 cents: I had the same problem, in WIdnows environment. It was fixed by installing node.js.
As this changes the PATH adding "C:\Program Files\nodejs\" in it, maybe this is the source of the problem. I have tried all the other suggested fix without success.
Hope this helps someone
