### ISSUE TITLE
Linter dies with underscore in variable name with "camelcase": true

### ISSUE THREAD

**Issue by newmanw** [AtomLinter/linter-jshint#197] opened 2016-01-25 20:20 UTC
Given a file with this single line of code;

```javascript
  var no_camel_case = "foo";
```

With camelcase jshint option set:

```javascript
  "camelcase": true
```

Dies with:

```
Uncaught TypeError: Invalid Point: (11, NaN)

TypeError: Invalid Point: (11, NaN)
    at Function.module.exports.Point.assertValid (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/point.js:63:15)
    at TextBuffer.module.exports.TextBuffer.clipPosition (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1015:13)
    at TextBuffer.module.exports.TextBuffer.clipRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1003:20)
    at MarkerLayer.module.exports.MarkerLayer.markRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker-layer.js:204:46)
    at TextEditorMarkerLayer.module.exports.TextEditorMarkerLayer.markBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-marker-layer.js:78:52)
    at DisplayBuffer.module.exports.DisplayBuffer.markBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1100:38)
    at TextEditor.module.exports.TextEditor.markBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1339:59)
    at /Users/wnewman/.atom/packages/linter/lib/editor-linter.js:50:34
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at EditorLinter.addMessage (/Users/wnewman/.atom/packages/linter/lib/editor-linter.js:137:20)
    at /Users/wnewman/.atom/packages/linter/lib/linter-views.js:104:22
    at Array.forEach (native)
    at LinterViews.notifyEditorLinters (/Users/wnewman/.atom/packages/linter/lib/linter-views.js:102:11)
    at LinterViews.render (/Users/wnewman/.atom/packages/linter/lib/linter-views.js:59:10)
    at /Users/wnewman/.atom/packages/linter/lib/linter.coffee:39:14
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at MessageRegistry.updatePublic (/Users/wnewman/.atom/packages/linter/lib/message-registry.js:84:18)
    at UpdateMessages (/Users/wnewman/.atom/packages/linter/lib/message-registry.js:24:16)
```

If I set "camelcase": false the linter will not die.

https://github.com/atom-community/linter/issues/1057

**Comment by danielbarela** [comment] 2016-01-26 16:19
This appears to be caused by an error in jshint: https://github.com/jshint/jshint/issues/2845 pull request: https://github.com/jshint/jshint/pull/2846

**Comment by Arcanemagus** [comment] 2016-01-26 17:36
Thanks for figuring that out @danielbarela! Marking this as closed since this is an external bug.

**Comment by newmanw** [comment] 2016-01-26 17:58
IMHO this should not be closed,  you depend on a 3rd party library that has a bug, and that bug causes linter-jshint to crash. 

At some point jshint will merge PR jshint/jshint#2846 , update the version, and publish to npm.  At that point I would argue that the package.json in this project should be updated to pull that version.  Where is that tracked?

**Comment by steelbrain** [comment] 2016-01-26 17:59
Blocked at jshint/jshint#2846

**Comment by Arcanemagus** [comment] 2016-02-15 20:16
Still waiting on a release that includes https://github.com/jshint/jshint/commit/480252a89beff62f07c7c316d97f5ef741f4664c :disappointed:.

**Comment by Arcanemagus** [comment] 2016-02-24 22:00
Looks like they still haven't released a new version yet.

**Comment by Arcanemagus** [comment] 2016-05-06 18:26
`jshint@2.9.2` fixes this, and was included in https://github.com/AtomLinter/linter-jshint/pull/266, since this is usinga caret range re-installing the package will update to the current version for you. I'll probably be pushing out a release for other things later which will bump the minimum version.

**Closed by Arcanemagus** 2016-05-06 18:26 UTC
Labels: Bug, External
