### ISSUE TITLE
Config.unobserve is deprecated.

### ISSUE THREAD

**Issue by corporatepiyush** [AtomLinter/linter-jshint#54] opened 2015-04-03 07:32 UTC
Config::unobserve no longer does anything. Call `.dispose()` on the object returned by Config::observe instead.
```
Config.unobserve (C:\Users\pkatariy\AppData\Local\atom\app-0.189.0\resources\app\src\config.js:374:19)
LinterJshint.destroy (C:\Users\pkatariy\.atom\packages\linter-jshint\lib\linter-jshint.coffee:52:16)
```

**Comment by clarkbw** [comment] 2015-04-11 15:51
dupe of #52

**Closed** 2015-04-11 15:57 UTC
