### ISSUE TITLE
Invalid position given by 'W043'

### ISSUE THREAD

**Issue by interbiznw** [AtomLinter/linter-jshint#508] opened 2017-09-14 19:58 UTC
JSHint returned a point that did not exist in the document being edited.
Rule: `W043`
Requested point: 643:51

Debug information:
```
Atom version: 1.20.0
linter-jshint version: v3.1.5
JSHint version: jshint v2.9.5
Hours since last Atom restart: 0.1
Platform: win32
Current file's scopes: [
  "source.js"
]
linter-jshint configuration: {
  "executablePath": "",
  "lintInlineJavaScript": false,
  "disableWhenNoJshintrcFileInPath": false,
  "scopes": [
    "source.js",
    "source.js-semantic"
  ],
  "jshintFileName": ".jshintrc",
  "jshintignoreFilename": ".jshintignore"
}
```

**Comment by Arcanemagus** [comment] 2017-09-14 22:36
Please see the following issue for more details and a temporary workaround.

Thanks for taking the time to report this!

**Comment by Arcanemagus** [comment] 2017-09-14 22:36
Duplicate of #439

**Closed by Arcanemagus** 2017-09-14 22:36 UTC
