### ISSUE TITLE
JSHint returning invalid response

### ISSUE THREAD

**Issue by mcbanderson** [AtomLinter/linter-jshint#260] opened 2016-04-14 20:29 UTC
After upgrading to the latest version (2.1.0) I started getting the error message "JSHint return an invalid response, check your console for more info".

I checked the configuration and everything appears to be set up correctly. Anyone have any idea what could be causing this? Appears to be similar to issues #130, #124.

I am running Atom on Windows 10.

**Comment by Arcanemagus** [comment] 2016-04-14 20:42
Duplicate of #238, which seems to be caused by an Electron bug inside Atom, I've filed https://github.com/atom/atom/issues/11471 to try to get that figured out.

[This comment](https://github.com/AtomLinter/linter-jshint/issues/238#issuecomment-210119451) shows probably the safest workaround for right now.

Marking this as closed, thanks for reporting though!

**Closed by Arcanemagus** 2016-04-14 20:42 UTC

**Comment by mcbanderson** [comment] 2016-04-14 22:09
Thanks for the quick response! I went ahead and downgraded Atom to 1.6.2 as you suggested in the other post and that fixed the problem.

**Comment by Arcanemagus** [comment] 2016-04-15 03:30
Atom v1.7.1 (And v1.8.0-beta1) has been released which should fix this. If you are still having issues please re-open this or file a new issue.
