### ISSUE TITLE
typeof statement throws error when unfinished

### ISSUE THREAD

**Issue by VesterDe** [AtomLinter/linter-jshint#171] opened 2015-09-28 13:07 UTC
To trigger anywhere:

```javascript
console.log(typeof);
```

**Comment by Arcanemagus** [comment] 2015-09-28 16:00
Shouldn't this be the _desired_ behavior, since that isn't valid?

In any case, even if that isn't what it should be doing, this would be an issue with `jshint` itself, as this package simply runs that utility.

**Comment by SpainTrain** [comment] 2015-09-28 16:03
Agreed, that example is not valid syntax (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/typeof)

**Comment by Arcanemagus** [comment] 2015-09-28 16:03
After forcing this linter to run I got the following stack trace:
```
Error: C:\Users\Landon\.atom\packages\linter-jshint\node_modules\jshint\src\jshint.js:5521
        throw err;
              ^
TypeError: Cannot read property 'identifier' of undefined
    at Object.nud (C:\Users\Landon\.atom\packages\linter-jshint\node_modules\jshint\src\jshint.js:2396:10)
    at expression (C:\Users\Landon\.atom\packages\linter-jshint\node_modules\jshint\src\jshint.js:888:34)
    at C:\Users\Landon\.atom\packages\linter-jshint\node_modules\jshint\src\jshint.js:2512:23
    at Object.x.led (C:\Users\Landon\.atom\packages\linter-jshint\node_modules\jshint\src\jshint.js:1157:16)
    at expression (C:\Users\Landon\.atom\packages\linter-jshint\node_modules\jshint\src\jshint.js:928:36)
    at statement (C:\Users\Landon\.atom\packages\linter-jshint\node_modules\jshint\src\jshint.js:1635:9)
    at statements (C:\Users\Landon\.atom\packages\linter-jshint\node_modules\jshint\src\jshint.js:1678:16)
    at block (C:\Users\Landon\.atom\packages\linter-jshint\node_modules\jshint\src\jshint.js:1797:13)
    at doFunction (C:\Users\Landon\.atom\packages\linter-jshint\node_modules\jshint\src\jshint.js:3103:5)
    at Object.fud (C:\Users\Landon\.atom\packages\linter-jshint\node_modules\jshint\src\jshint.js:3829:5)
  at exit (C:\Users\Landon\.atom\packages\linter-jshint\node_modules\atom-linter\lib\helpers.coffee:32:24)
  at triggerExitCallback (C:\Users\Landon\AppData\Local\atom\app-1.0.19\resources\app.asar\src\buffered-process.js:213:47)
  at ChildProcess.<anonymous> (C:\Users\Landon\AppData\Local\atom\app-1.0.19\resources\app.asar\src\buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:172:7)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

**Comment by Arcanemagus** [comment] 2015-09-28 16:07
Okay, I'm getting this on the command line as well, so this is a bug in `jshint` itself, not `linter-jshint`. I'll file an issue over there.

**Comment by VesterDe** [comment] 2015-09-28 16:19
I wasn't saying my exmple should be viable code :) Thanks for double checking.

**Comment by Arcanemagus** [comment] 2015-09-28 16:38
Looks like this should be fixed in v2.9.0 of `jshint` (in [this issue](https://github.com/jshint/jshint/pull/2508)), but for some reason that isn't marked as the latest release yet.

**Comment by Arcanemagus** [comment] 2015-10-01 18:02
@VesterDe can you close this issue as it isn't actually a problem with `linter-jshint`?

**Closed** 2015-10-01 18:36 UTC

**Comment by Arcanemagus** [comment] 2015-10-01 18:42
Thanks!

**Comment by VesterDe** [comment] 2015-10-01 19:33
Thank _you_, it was my first ever ticket :)

**Comment by SpainTrain** [comment] 2015-10-01 19:36
> Thank you, it was my first ever ticket :)

:tada:

**Comment by Arcanemagus** [comment] 2015-10-01 20:17
You have to start somewhere :wink:

Looks like the regression issue was just fixed a day ago, so hopefully `jshint` 2.9.1 will be released soon.

**Comment by ricardograca** [comment] 2016-01-19 10:33
Well, it wasn't released soon, but 5 days ago: https://github.com/jshint/jshint/releases/tag/2.9.1

Better late than never :)

**Comment by Arcanemagus** [comment] 2016-01-19 19:21
Good to hear, thanks for the update @ricardograca!
