### ISSUE TITLE
Invalid position given by 'W033'

### ISSUE THREAD

**Issue by JoeChapman82** [AtomLinter/linter-jshint#454] opened 2017-07-10 07:52 UTC
JSHint returned a point that did not exist in the document being edited.
Rule: `W033`
Requested start point: 7:91

Debug information:
```
Atom version: 1.18.0
linter-jshint version: v3.1.4
JSHint version: jshint v2.9.5
Hours since last Atom restart: 5.6
Platform: darwin
Current file's scopes: [
  "source.js",
  "variable.other.property.js"
]
linter-jshint configuration: {
  "executablePath": "",
  "lintInlineJavaScript": false,
  "disableWhenNoJshintrcFileInPath": false,
  "scopes": [
    "source.js",
    "source.js-semantic"
  ],
  "jshintFileName": ".jshintrc",
  "jshintignoreFilename": ".jshintignore"
}
```

**Comment by Arcanemagus** [comment] 2017-07-10 15:56
Closing as a duplicate of #422. Please see that issue for more details (and update `linter-jshint` as the current version would have directed you there).

**Closed by Arcanemagus** 2017-07-10 15:56 UTC
