### ISSUE TITLE
Invalid position given by 'W069'

### ISSUE THREAD

**Issue by Seth10001** [AtomLinter/linter-jshint#486] opened 2017-08-21 20:06 UTC
JSHint returned a point that did not exist in the document being edited.
Rule: `W069`
Requested point: 62:59

Debug information:
```
Atom version: 1.19.2
linter-jshint version: v3.1.5
JSHint version: jshint v2.9.5
Hours since last Atom restart: 0.9
Platform: darwin
Current file's scopes: [
  "source.js",
  "meta.brace.curly.js"
]
linter-jshint configuration: {
  "lintInlineJavaScript": true,
  "scopes": [
    "source.js",
    "source.js-semantic",
    "source.js.jsx"
  ],
  "executablePath": "",
  "disableWhenNoJshintrcFileInPath": false,
  "jshintFileName": ".jshintrc",
  "jshintignoreFilename": ".jshintignore"
}
```

**Comment by Arcanemagus** [comment] 2017-08-21 21:03
Please see the following issue for more information on this bug.

**Comment by Arcanemagus** [comment] 2017-08-21 21:03
Duplicate of https://github.com/AtomLinter/linter-jshint/issues/460

**Closed by Arcanemagus** 2017-08-21 21:03 UTC
