### ISSUE TITLE
Invalid Result recieved from JSHint

### ISSUE THREAD

**Issue by dgautsch** [AtomLinter/linter-jshint#121] opened 2015-07-10 20:36 UTC
<img width="759" alt="screen shot 2015-07-10 at 4 36 15 pm" src="https://cloud.githubusercontent.com/assets/165664/8628512/ad013a56-2721-11e5-9275-eb8a264b7cd0.png">

After installing the latest linter-jshint and linter I am now receiving these errors and linting does not work.

**Comment by steelbrain** [comment] 2015-07-10 20:37
Dupe of https://github.com/AtomLinter/linter-jshint/issues/117
Please move the discussion over to https://github.com/AtomLinter/Linter/issues/726

**Closed by steelbrain** 2015-07-10 20:37 UTC
