### ISSUE TITLE
Folder overrides ignored

### ISSUE THREAD

**Issue by surdu** [AtomLinter/linter-jshint#367] opened 2017-02-13 12:03 UTC
I have a .jshintrc file inside a folder that I want to override a global .jshintrc in my project. No matter what I write in that file, it is ignored.

I know for sure it is ignored because if the project-level .jshintrc is invalid, linter-jshint throws an error, whereas if I make the .jshintrc from the folder-level invalid, I see no error.

The project is available here: https://github.com/surdu/selector-to-tag . The folder in question is `spec`.

===Versions

Atom: 1.15.0-beta1 x64
linter-jshint: 3.0.2

**Comment by Arcanemagus** [comment] 2017-05-02 22:51
Using https://github.com/surdu/selector-to-tag/commit/0bcf1866c8ac9dacaf08a23f68e075fa7f3e5e0f as a base for the test, and adding `var foo = bar;` to the `selector-solver-spec.js` file.

With the configurations as given in that commit and the change above there are two messages shown:
![image](https://cloud.githubusercontent.com/assets/427137/25642455/ca25194a-2f4e-11e7-8e40-44570aa24bf0.png)

Adding `"unused": false,` to the `.jshintrc` file in the `spec` folder leads to only one message remaining:
![image](https://cloud.githubusercontent.com/assets/427137/25642479/f1e00bfc-2f4e-11e7-8387-bff18e347783.png)

Note that setting `undef` to `false` still shows undefined messages... even if both files are set to `false`. This seems to be yet another bug in JSHint itself.

I'm marking this as closed since I'm unable to reproduce this, if you can provide more detailed steps to reproduce this I would be happy to test again!

**Closed by Arcanemagus** 2017-05-02 22:51 UTC
