### ISSUE TITLE
LinterJshint.Linter is deprecated.

### ISSUE THREAD

**Issue by ArekSredzki** [AtomLinter/linter-jshint#114] opened 2015-07-09 17:21 UTC
AtomLinter v0.X.Y API has been deprecated. Please refer to the Linter docs to update and the latest API: https://github.com/AtomLinter/Linter/wiki/Migrating-to-the-new-API
```
LinterJshint.Linter (/Users/areksredzki/.atom/packages/linter/lib/linter.coffee:60:4)
new LinterJshint (/Users/areksredzki/.atom/packages/linter-jshint/lib/linter-jshint.coffee:35:4)
Object.lint (/Users/areksredzki/.atom/packages/linter/lib/legacy.coffee:61:21)
<unknown> (/Users/areksredzki/.atom/packages/linter/lib/editor-linter.coffee:69:25)
currentLinter (/Users/areksredzki/.atom/packages/linter/lib/editor-linter.coffee:68:19)
<unknown> (/Users/areksredzki/.atom/packages/linter/lib/editor-linter.coffee:82:22)
```

**Comment by iam4x** [comment] 2015-07-09 18:35
Dupe of #111

**Closed by iam4x** 2015-07-09 18:35 UTC
