### ISSUE TITLE
Link to errors are broken

### ISSUE THREAD

**Issue by surdu** [AtomLinter/linter-jshint#341] opened 2016-09-26 16:23 UTC
In the error panel, the Wxxx errors link to a domain that appears to have been taken by domain scalpers: http://jslinterrors.com/

**Comment by Arcanemagus** [comment] 2016-09-26 19:19
Closing as a duplicate of #316, fixed in #337... and apparently not released yet, which I'll do right now 😛.

**Closed by Arcanemagus** 2016-09-26 19:19 UTC

**Comment by surdu** [comment] 2016-09-27 06:56
Sorry, searched only opene tickets 😞

**Comment by Arcanemagus** [comment] 2016-09-27 16:18
No worries, it should have been released a while ago, sorry!
