### ISSUE TITLE
Regression : linter-jshint no longer works with language-babel

### ISSUE THREAD

**Issue by awilkins** [AtomLinter/linter-jshint#349] opened 2016-10-03 09:48 UTC
Commit 4364381935010ae271a36b77e76b3756271bb86d added the `source.js.jsx` scope that `language-babel` uses - this was lost when the Coffeescript version of the linter was blown away and replaced.

I've just added 'source.js.jsx' to the list of scopes on line 38 of `lib/main.js` and it seems to work OK.

Is there a deeper reason for avoiding linting this scope? I understand if jshint can't cope with e.g. JSX ; in that case you could argue that the problem is with `language-babel` which should probably dynamically declare the right scope (ie - only add .jsx when JSX features are present).

**Comment by Arcanemagus** [comment] 2016-10-03 17:04
Closing as a duplicate of #348.

Basically I got tired of seeing bugs related to running on JSX code being reported, and JSHint itself claims no support of JSX as far as I can see. If you can find evidence that it _should_ be working on there then we can add it back (buggy as it is). I would _highly_ recommend moving to a linter that is actually designed to handle JSX though, such as ESLint with the proper parser + plugins.

**Closed by Arcanemagus** 2016-10-03 17:04 UTC

**Comment by Arcanemagus** [comment] 2016-10-03 17:05
Actually, just re-read your message again a little more carefully. If `language-babel` is declaring _regular_ JS as JSX that is definitely a bug in `language-babel` that should be reported there.
