### ISSUE TITLE
Option to force lint by file extension or scope

### ISSUE THREAD

**Issue by augusto-moura** [AtomLinter/linter-jshint#372] opened 2017-03-20 18:32 UTC
There's a chance of adding a option forcing the linter to lint all files ending with `.js`? I want to use it with the package `language-babel` (primarily because of the es6 grammar), but it forces all JavaScript files to `source.js.jsx`. Maybe force to lint only certain scopes.

**Comment by Arcanemagus** [comment] 2017-03-20 22:02
This is a bug with `language-babel` that they marked as invalid, so it's highly unlikely to ever be fixed: https://github.com/gandm/language-babel/issues/266

JSHint has no support for JSX so unfortunately that scope can't be added to the list of allowed scopes here.

**Comment by Arcanemagus** [comment] 2017-03-20 22:04
Closing as a duplicate of https://github.com/AtomLinter/linter-jshint/issues/348, I wish there was more that could be done here. I would just recommend using the built in `language-javascript` as it works perfectly fine.

**Comment by augusto-moura** [comment] 2017-03-21 12:54
It's not a duplicate, I'm asking for a field in the settings for force scopes to be linted, configurable by the user. I already do that editing the `main.js` of the apm package, but it's like a workaround, every update breaks it. I can work on a PR adding the option if I have the time, I think it's quite simple.

I use `language-babel` with plain js most of the time, and JSHint can handle that. JSX projects generally don't have a `.jshintrc` (because, as already said, jshint doesn't supports JSX) so enabling `Disable When No Jshintrc File In Path` option and forcing `source.js.jsx` scope works in most of the cases.

**Comment by Arcanemagus** [comment] 2017-03-21 16:56
I'd definitely be open to that, we have something similar in `linter-eslint` since it actually can support many different scopes.

**Closed** 2017-05-05 16:20 UTC
Labels: Enhancement
