### ISSUE TITLE
Invalid position given by 'W069'

### ISSUE THREAD

**Issue by Yangholmes** [AtomLinter/linter-jshint#462] opened 2017-07-25 01:04 UTC
JSHint returned a point that did not exist in the document being edited.
Rule: `W069`
Requested point: 73:47

Debug information:
```
Atom version: 1.18.0
linter-jshint version: v3.1.5
JSHint version: jshint v2.9.5
Hours since last Atom restart: 0.2
Platform: win32
Current file's scopes: [
  "source.js",
  "variable.other.object.js"
]
linter-jshint configuration: {
  "executablePath": "",
  "lintInlineJavaScript": false,
  "disableWhenNoJshintrcFileInPath": false,
  "scopes": [
    "source.js",
    "source.js-semantic"
  ],
  "jshintFileName": ".jshintrc",
  "jshintignoreFilename": ".jshintignore"
}
```

**Comment by Arcanemagus** [comment] 2017-07-25 15:58
Duplicate of #460, see that issue for more information.

**Closed by Arcanemagus** 2017-07-25 15:58 UTC
Labels: Duplicate, External

**Comment by Yangholmes** [comment] 2017-07-27 12:46
OK, THX.
