### ISSUE TITLE
Invalid position given by 'W043'

### ISSUE THREAD

**Issue by gyutaesi** [AtomLinter/linter-jshint#506] opened 2017-09-13 11:13 UTC
JSHint returned a point that did not exist in the document being edited.
Rule: `W043`
Requested point: 15:78

Debug information:
```
Atom version: 1.19.7
linter-jshint version: v3.1.5
JSHint version: jshint v2.9.5
Hours since last Atom restart: 3.4
Platform: win32
Current file's scopes: [
  "source.js",
  "meta.method-call.js",
  "meta.arguments.js",
  "meta.brace.curly.js"
]
linter-jshint configuration: {
  "executablePath": "",
  "lintInlineJavaScript": false,
  "disableWhenNoJshintrcFileInPath": false,
  "scopes": [
    "source.js",
    "source.js-semantic"
  ],
  "jshintFileName": ".jshintrc",
  "jshintignoreFilename": ".jshintignore"
}
```

**Comment by Arcanemagus** [comment] 2017-09-13 16:59
Duplicate of #439

**Comment by Arcanemagus** [comment] 2017-09-13 17:00
Please see the linked issue for more information.

**Closed by Arcanemagus** 2017-09-13 16:59 UTC
