### ISSUE TITLE
Invalid position given by 'W033'

### ISSUE THREAD

**Issue by MathieuLopes** [AtomLinter/linter-jshint#424] opened 2017-06-26 09:55 UTC
JSHint returned a point that did not exist in the document being edited.
Rule: `W033`
Requested start point: 131:75

Debug information:
```
Atom version: 1.17.2
linter-jshint version: v3.1.4
JSHint version: jshint v2.9.5
Hours since last Atom restart: 1.8
Platform: darwin
Current file's scopes: [
  "source.js",
  "meta.method-call.js",
  "meta.arguments.js"
]
linter-jshint configuration: {
  "executablePath": "",
  "lintInlineJavaScript": false,
  "disableWhenNoJshintrcFileInPath": false,
  "scopes": [
    "source.js",
    "source.js-semantic"
  ],
  "jshintFileName": ".jshintrc",
  "jshintignoreFilename": ".jshintignore"
}
```

**Comment by Arcanemagus** [comment] 2017-06-26 15:51
Is your file indented using tabs?

**Comment by Arcanemagus** [comment] 2017-06-29 23:29
Closing as a duplicate of #422, if your files _aren't_ indented by tabs please give an example file and reopen this issue.

**Closed by Arcanemagus** 2017-06-29 23:29 UTC
