### ISSUE TITLE
Invalid position given by 'W043'

### ISSUE THREAD

**Issue by jeongsangah** [AtomLinter/linter-jshint#470] opened 2017-07-31 04:56 UTC
JSHint returned a point that did not exist in the document being edited.
Rule: `W043`
Requested point: 16:29

Debug information:
```
Atom version: 1.18.0
linter-jshint version: v3.1.5
JSHint version: jshint v2.9.5
Hours since last Atom restart: 0.1
Platform: win32
Current file's scopes: [
  "unknown"
]
linter-jshint configuration: {
  "executablePath": "",
  "lintInlineJavaScript": false,
  "disableWhenNoJshintrcFileInPath": false,
  "scopes": [
    "source.js",
    "source.js-semantic"
  ],
  "jshintFileName": ".jshintrc",
  "jshintignoreFilename": ".jshintignore"
}
```

**Comment by Arcanemagus** [comment] 2017-07-31 20:43
Assuming that your code is indented using tabs I'm marking this as a duplicate of #439. Please see that issue for more information. If your code _isn't_ indented with tabs can you please provide an example file to reproduce this?

**Closed by Arcanemagus** 2017-07-31 20:43 UTC
Labels: Duplicate
