### ISSUE TITLE
jslinterrors.com is down

### ISSUE THREAD

**Issue by menixator** [AtomLinter/linter-jshint#333] opened 2016-09-12 12:31 UTC
Just bringing to your attention that the site that the package redirects you whenever you click an error code(such as `W033`) from the error panel is down.

**Comment by Arcanemagus** [comment] 2016-09-12 18:22
Duplicate of #316. It seems that nobody who uses this package cares enough to actually fix it though, so I'll take care of it in a few minutes.

**Closed by Arcanemagus** 2016-09-12 18:22 UTC
