### ISSUE TITLE
Invalid position given by 'W033'

### ISSUE THREAD

**Issue by mikosurge** [AtomLinter/linter-jshint#725] opened 2019-04-04 04:53 UTC
JSHint returned a point that did not exist in the document being edited.
Rule: `W033`
Requested point: 19:157

Debug information:
```
Atom version: 1.35.1
linter-jshint version: v3.1.15
JSHint version: jshint v2.10.2
Hours since last Atom restart: 1.1
Platform: win32
Current file's scopes: [
  "source.js"
]
linter-jshint configuration: {
  "executablePath": "C:\\Users\\nam.phungthanh\\.atom\\packages\\linter-jshint\\node_modules\\jshint\\bin\\jshint",
  "lintInlineJavaScript": true,
  "disableWhenNoJshintrcFileInPath": false,
  "scopes": [
    "source.js",
    "source.js-semantic"
  ],
  "jshintFileName": ".jshintrc",
  "jshintignoreFilename": ".jshintignore"
}
```

**Comment by Arcanemagus** [comment] 2019-04-04 16:50
Please see the following issue for more details and a temporary workaround.

Thanks for taking the time to report this!

**Comment by Arcanemagus** [comment] 2019-04-04 16:50
Duplicate of #422

**Closed by Arcanemagus** 2019-04-04 16:50 UTC
