### ISSUE TITLE
Does not work with Linter 1.0.0

### ISSUE THREAD

**Issue by Cortys** [AtomLinter/linter-jshint#100] opened 2015-06-25 00:10 UTC
Using Atom 0.211 on OS X 10.10.3. No other JS linters active.

**Comment by Eschon** [comment] 2015-06-25 09:51
It works fine for me with Atom 0.211, linter 1.0.4 and linter-jshint 0.1.6 on OS X 10.10.3.
Maybe try updating linter

**Comment by Cortys** [comment] 2015-06-25 19:28
@Eschon I'm using linter 1.0.4 as well, experiencing the issue since 1.0.0 though.

**Comment by nicolasbrugneaux** [comment] 2015-06-25 20:11
Doesn't work for me either :(

**Comment by AsaAyers** [comment] 2015-06-25 20:14
There's still nothing in this issue that we can investigate to fix it. There are no steps to reproduce the issue, there is no error.

**Comment by Cortys** [comment] 2015-06-25 20:23
Sorry. Didn't have the time to look further into this yet.

Apparently linting fails if the "Disable when no .jshintrc file found in path" flag is set. That's all it needs (for me) to reproduce the issue.

**Comment by varemenos** [comment] 2015-06-25 20:51
I also have the "Disable when no .jshintrc file found in path" flag is set and it doesn't work.
There is a `.jshintrc` file in the root of the project

**Comment by AsaAyers** [comment] 2015-06-25 20:57
Thanks, I'm bringing this up in the #linter room on [Atom Slack](http://atom-slack.herokuapp.com/). This sounds familiar and I thought this got resolved.

I'm part of the team working on `linter`, so I haven't really worked on `linter-jshint`

**Comment by AsaAyers** [comment] 2015-06-25 21:21
This is actually a duplicate of #40

**Closed by AsaAyers** 2015-06-25 21:21 UTC

**Comment by AsaAyers** [comment] 2015-06-25 21:26
I just published linter-jshint@v0.1.7 which should fix this.

**Comment by Cortys** [comment] 2015-06-25 22:12
It works. Thanks a lot!
