### ISSUE TITLE
Invalid position given by 'W069'

### ISSUE THREAD

**Issue by dlefcoe** [AtomLinter/linter-jshint#534] opened 2017-10-25 22:32 UTC
JSHint returned a point that did not exist in the document being edited.
Rule: `W069`
Requested point: 99:36

Debug information:
```
Atom version: 1.17.0
linter-jshint version: v3.1.6
JSHint version: jshint v2.9.5
Hours since last Atom restart: 2.7
Platform: win32
Current file's scopes: [
  "source.js",
  "punctuation.terminator.statement.js"
]
linter-jshint configuration: {
  "executablePath": "",
  "lintInlineJavaScript": false,
  "disableWhenNoJshintrcFileInPath": false,
  "scopes": [
    "source.js",
    "source.js-semantic"
  ],
  "jshintFileName": ".jshintrc",
  "jshintignoreFilename": ".jshintignore"
}
```

**Comment by Arcanemagus** [comment] 2017-10-25 23:03
Please see the following issue for more information on this bug.

**Comment by Arcanemagus** [comment] 2017-10-25 23:03
Duplicate of https://github.com/AtomLinter/linter-jshint/issues/460

**Closed by Arcanemagus** 2017-10-25 23:03 UTC
