### ISSUE TITLE
JSHint return an invalid response, check your console for more info

### ISSUE THREAD

**Issue by roqueorts** [AtomLinter/linter-jshint#258] opened 2016-04-14 08:38 UTC
I get this error when I open one specific file.

**Comment by hasanlussa** [comment] 2016-04-14 08:47
+1

**Comment by gregtyler** [comment] 2016-04-14 09:26
I'm seeing this too, since upgrading to Atom 1.7.0 this morning, in all JavaScript files I open.

I'm running version 1.11.4 of linter and 2.1.0 of linter-jshint. My operating system is Windows 7.

Opening the console, the error is "SyntaxError: Unexpected end of input". Trace:
```
(anonymous function)	@	main.js:126
step	@	/C:/Users/ggiltrow/.atom/packages/linter-jshint/lib/main.js:3
_tickCallback	@	node.js:392
```

**Comment by icaruus** [comment] 2016-04-14 09:37
Same for me, Atom 1.7.0, Windows 7, linter-jshint 2.1.0.
Console:

`[Linter-JSHint] SyntaxError: Unexpected end of input(…)
(anonymous function) @ main.js:126`

**Comment by BlaM** [comment] 2016-04-14 10:15
Same here, exactly stating at the moment Atom updated to 1.7.0. However the error is reported in line 123, not in 126 for me:

    [Linter-JSHint] SyntaxError: Unexpected end of input
    at Object.parse (native)
    at Object.<anonymous> (.../packages/linter-jshint/lib/main.js:124:25)
    at [object Generator].next (native)
    at step (...\packages\linter-jshint\lib\main.js:3:273)
    at process._tickCallback (node.js:392:9)

      (anonymous function) @ .../packages/linter-jshint/lib/main.js:123

Windows 8.1 for me

**Comment by gregtyler** [comment] 2016-04-14 10:40
I've done a bit of loose digging, and it looks like the `Helpers.execNode` command returns an empty string rather than JSON as expected. Running the same command in the terminal though, I get the expected response back. So the command is fine, but running it from Node isn't working.

I believe `Helpers.execNode` traces back to the "exec" function in `node_modules/atom-linter/lib/helpers.js`, but I'm not particularly familiar with node internals and yields, so I can't really dig much further.

**Comment by Whipgit** [comment] 2016-04-14 12:51
+1

**Comment by cakenggt** [comment] 2016-04-14 12:55
+1
```[Linter-JSHint] SyntaxError: Unexpected end of input(…) (anonymous function) @ /C:/Users/cakenggt/.atom/packages/linter-jshint/lib/main.js:123```

**Comment by ZStelmo** [comment] 2016-04-14 13:10
Same where.

**Comment by champunes** [comment] 2016-04-14 13:30
+1
I detected the problem after auto-update of my Atom to 1.7.0 in Windows.

**Comment by dhprototype** [comment] 2016-04-14 13:56
Exact same error as @Whipgit 

Windows 7 Pro
Atom 1.7.0
linter-jshint: 2.1.0
atom-linter: 4.6.1

**Comment by cristian-sima** [comment] 2016-04-14 14:16
+1

**Comment by Arcanemagus** [comment] 2016-04-14 17:04
Closing as a duplicate of #238, it definitely looks like something broke in Atom's BufferedNodeProcess (which `execNode` wraps around) with the v1.7.0 update on Windows.

**Closed by Arcanemagus** 2016-04-14 17:04 UTC
