### ISSUE TITLE
gulpfile.babel.js error

### ISSUE THREAD

**Issue by genoma** [AtomLinter/linter-jshint#209] opened 2016-02-12 10:12 UTC
While linting gulpfile.bable.js Atom throws an error related, I believe, to linter-jshint. 

```
TypeError: Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at TextBuffer.module.exports.TextBuffer.lineLengthForRow (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:460:29)
    at /Users/jenoma/.atom/packages/linter-jshint/lib/main.coffee:86:47
    at Array.map (native)
    at /Users/jenoma/.atom/packages/linter-jshint/lib/main.coffee:77:25
```

Could you please have a look at it?
Thanks.

**Comment by Arcanemagus** [comment] 2016-02-12 17:23
Can you post your `gulpfile.bable.js` so that we can reproduce this?

**Comment by genoma** [comment] 2016-02-15 08:39
I've created a Gist for you, let me know if you need something else.
https://gist.github.com/genoma/e07ab7770e38dc6edbba

Thanks in advance.

**Comment by daltones** [comment] 2016-02-15 16:30
I've been seeing this error last days. Then I realize that the problem was with my .jshintrc file.

I was using ```"es5": true``` and new versions of jshint ouputs ```ES5 option is now set per default```. And then somehow linter-jshint crashes.

Dropping es5 option solved the problem for me.

**Comment by Arcanemagus** [comment] 2016-02-15 17:06
I bet you that it's outputting that directly to `stdout` (instead of `stderr` which would be handled properly and report to the user...).

This plugin requests a JSON output, and it's feeding that sentence to it raw... which is invalid JSON. I'll see if I have time later today to throw together a fix as it looks like this package doesn't have a maintainer currently.

**Comment by steelbrain** [comment] 2016-02-15 19:46
JSON parsing error fixed by https://github.com/AtomLinter/linter-jshint/pull/210

**Comment by Arcanemagus** [comment] 2016-02-15 19:47
v2.0.0 has been published which should handle the JSON failing to parse properly and report it to the user, marking this as closed but if you have any further comments feel free to ask here :wink:.

**Closed by Arcanemagus** 2016-02-15 19:47 UTC
