### ISSUE TITLE
Error when starting a block comment (unclosed yet) inside an object

### ISSUE THREAD

**Issue by emileber** [AtomLinter/linter-jshint#292] opened 2016-06-17 20:46 UTC
When I type `/**` inside an object like in the following, linter-jshint throws an error.

```
var test = {
    /**
    prop: 2
);
```

# System and versions

**Atom Version**: 1.8.0
**System**: Windows 10 Pro 64 bits
**Package**: linter-jshint 2.1.0

## Installed packages

```
Community Packages (22) C:\Users\emile.bergeron.CAMINO\.atom\packages
├── atom-beautify@0.29.8
├── atom-terminal@0.8.0
├── autoclose-html@0.23.0
├── color-picker@2.1.1
├── docblockr@0.7.3
├── emmet@2.4.3
├── file-icons@1.7.15
├── foldername-tabs@0.1.11
├── git-plus@5.15.0
├── highlight-selected@0.11.2
├── linter@1.11.11
├── linter-jshint@2.1.0
├── linter-php@1.2.0
├── merge-conflicts@1.4.4
├── minimap@4.24.6
├── minimap-highlight-selected@4.4.0
├── open-recent@5.0.0
├── pigments@0.29.2
├── sass-compiler-autosave@0.5.0
├── split-diff@1.0.2
├── temporary-root@1.0.0
└── todo-show@1.6.0

└── (empty)
```

# Stack trace

```
Error: C:\Users\emile.bergeron.CAMINO\.atom\packages\linter-jshint\node_modules\jshint\src\jshint.js:5328
        throw err;
        ^

TypeError: Cannot read property 'id' of null
    at Object.x.nud (C:\Users\emile.bergeron.CAMINO\.atom\packages\linter-jshint\node_modules\jshint\src\jshint.js:3237:26)
    at expression (C:\Users\emile.bergeron.CAMINO\.atom\packages\linter-jshint\node_modules\jshint\src\jshint.js:898:34)
    at Object.fud (C:\Users\emile.bergeron.CAMINO\.atom\packages\linter-jshint\node_modules\jshint\src\jshint.js:3679:17)
    at expression (C:\Users\emile.bergeron.CAMINO\.atom\packages\linter-jshint\node_modules\jshint\src\jshint.js:895:32)
    at statement (C:\Users\emile.bergeron.CAMINO\.atom\packages\linter-jshint\node_modules\jshint\src\jshint.js:1645:9)
    at statements (C:\Users\emile.bergeron.CAMINO\.atom\packages\linter-jshint\node_modules\jshint\src\jshint.js:1691:16)
    at itself (C:\Users\emile.bergeron.CAMINO\.atom\packages\linter-jshint\node_modules\jshint\src\jshint.js:5307:9)
    at lint (C:\Users\emile.bergeron.CAMINO\.atom\packages\linter-jshint\node_modules\jshint\src\cli.js:495:8)
    at Object.<anonymous> (C:\Users\emile.bergeron.CAMINO\.atom\packages\linter-jshint\node_modules\jshint\src\cli.js:634:9)
    at Socket.<anonymous> (C:\Users\emile.bergeron.CAMINO\.atom\packages\linter-jshint\node_modules\jshint\node_modules\cli\cli.js:841:18)
    at parameters.exit (C:\Users\emile.bergeron.CAMINO\.atom\packages\linter-jshint\node_modules\atom-linter\lib\helpers.js:47:27)
    at triggerExitCallback (C:\Program Files (x86)\Atom\resources\app.asar\src\buffered-process.js:215:47)
    at ChildProcess.<anonymous> (C:\Program Files (x86)\Atom\resources\app.asar\src\buffered-process.js:237:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

**Comment by Arcanemagus** [comment] 2016-06-17 21:19
That error is being thrown from inside `jshint`, it looks like this is a duplicate of https://github.com/jshint/jshint/issues/2932.

**Closed by Arcanemagus** 2016-06-17 21:19 UTC
